# Generated by Django 4.0.2 on 2022-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(choices=[('UST', 'The Hong Kong University of Science and Technology'), ('CU', 'The Chinese University of Hong Kong'), ('HKU', 'The University of Hong Kong')], default='UST', max_length=3)),
            ],
        ),
    ]
